[project]
name = 'Decentralized-Market-Research-Survey-Management-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.analysis-coordination]
path = 'contracts/analysis-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-validation]
path = 'contracts/data-validation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
